'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { RasaRating as RasaRatingElement, defineCustomElement as defineRasaRating } from "@rasahq/chat-widget-ui/dist/components/rasa-rating.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type RasaRatingEvents = { onRatingSelected: EventName<CustomEvent<{ value: string }>> };

const RasaRating: StencilReactComponent<RasaRatingElement, RasaRatingEvents> = /*@__PURE__*/ createComponent<RasaRatingElement, RasaRatingEvents>({
    tagName: 'rasa-rating',
    elementClass: RasaRatingElement,
    react: React,
    events: { onRatingSelected: 'ratingSelected' } as RasaRatingEvents,
    defineCustomElement: defineRasaRating
});

export default RasaRating;
