'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { RasaConversationFeedback as RasaConversationFeedbackElement, defineCustomElement as defineRasaConversationFeedback } from "@rasahq/chat-widget-ui/dist/components/rasa-conversation-feedback.js";
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type RasaConversationFeedbackEvents = { onFeedbackSubmitted: EventName<CustomEvent<{ rating: 'positive' | 'negative'; helpful: boolean }>> };

const RasaConversationFeedback: StencilReactComponent<RasaConversationFeedbackElement, RasaConversationFeedbackEvents> = /*@__PURE__*/ createComponent<RasaConversationFeedbackElement, RasaConversationFeedbackEvents>({
    tagName: 'rasa-conversation-feedback',
    elementClass: RasaConversationFeedbackElement,
    // @ts-ignore - React type of Stencil Output Target may differ from the React version used in the Nuxt.js project, this can be ignored.
    react: React,
    events: { onFeedbackSubmitted: 'feedbackSubmitted' } as RasaConversationFeedbackEvents,
    defineCustomElement: defineRasaConversationFeedback
});

export default RasaConversationFeedback;
