'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { RasaLinkButton as RasaLinkButtonElement, defineCustomElement as defineRasaLinkButton } from "@rasahq/chat-widget-ui/dist/components/rasa-link-button.js";
import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import React from 'react';

type RasaLinkButtonEvents = NonNullable<unknown>;

const RasaLinkButton: StencilReactComponent<RasaLinkButtonElement, RasaLinkButtonEvents> = /*@__PURE__*/ createComponent<RasaLinkButtonElement, RasaLinkButtonEvents>({
    tagName: 'rasa-link-button',
    elementClass: RasaLinkButtonElement,
    react: React,
    events: {} as RasaLinkButtonEvents,
    defineCustomElement: defineRasaLinkButton
});

export default RasaLinkButton;
