export const DISCONNECT_TIMEOUT = 5000;

export const WIDGET_DEFAULT_CONFIGURATION = {
  AUTO_OPEN: false,
  BOT_ICON: '',
  DISPLAY_TIMESTAMP: false,
  ERROR_MESSAGE: 'Something bad happened',
  INPUT_MESSAGE_PLACEHOLDER: 'Type your message here',
  MESSAGE_DELAY: 100,
  MESSAGE_TIMESTAMP: '',
  STREAM_MESSAGES: false,
  WIDGET_SUBTITLE: '',
  WIDGET_TITLE: 'Rasa Widget',
  TOGGLE_FULLSCREEN: false,
  UNREAD_DISPLAY_ENABLED: false,
  USER_ID: '',
  WIDGET_ICON: '',
  INITIAL_PAYLOAD: '',
  SERVER_URL: '',
  REST_ENABLED: false
};
