name: Chat Widget

on:
  push:
    branches: main
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v 4.2.2
        with:
          token: ${{ secrets.RASABOT_PAT }}
          ref: ${{ github.head_ref }}   

      - name: Setup Node version
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm ci

      - name: Lerna - Lint check
        run: npm run lint

      - name: Lerna - Build
        run: npm run build
      
      - name: Lerna - Tests
        run: npm run test

      - name: E2E - Install dependencies
        run: npm run e2e:install

      - name: E2E - Run automation suite
        run: npm run e2e:run
